# Generated by Django 2.1.7 on 2019-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190223_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='on_publish',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
