# Generated by Django 2.1.7 on 2019-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190223_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/category/default.jpg', upload_to='images/category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post/default.jpg', upload_to='images/post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='on_publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile/default.jpg', upload_to='images/profile'),
        ),
    ]
