# Generated by Django 2.1.7 on 2019-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190223_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/blog/category/default.jpg', upload_to='images/blog/category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/blog/post/default.jpg', upload_to='images/blog/post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/blog/profile/default.jpg', upload_to='images/blog/profile'),
        ),
    ]
