# Generated by Django 2.1.7 on 2019-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190223_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='blog/default_category.jpg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default_post.jpg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blog/default_profile.jpg', upload_to='blog'),
        ),
    ]
